# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chgs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchgs.proto\x1a\x0c\x63ommon.proto\"\xbe\x01\n\nchgsconfig\x12\x32\n\x10\x62ox_is_installed\x18\x01 \x01(\x0e\x32\x18.chgsconfig.boxinstalled\x12\x16\n\x0e\x63harge_current\x18\x02 \x01(\r\x12\x15\n\rbluetoothname\x18\x03 \x01(\t\x12\x1d\n\x15\x63harge_transaction_id\x18\x04 \x01(\r\".\n\x0c\x62oxinstalled\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x11\n\rBOX_INSTALLED\x10\x01\"\x98\x01\n\x14\x63hgs_content_wrapper\x12\x13\n\x0b\x63ommand_uid\x18\x01 \x01(\r\x12\x18\n\x10protocol_version\x18\x02 \x01(\r\x12!\n\nchgsconfig\x18\x03 \x01(\x0b\x32\x0b.chgsconfigH\x00\x12#\n\x0b\x63\x65rtificate\x18\x04 \x01(\x0b\x32\x0c.certificateH\x00\x42\t\n\x07\x63ommand\"w\n\x16\x63hgs_transport_wrapper\x12\x33\n\x14\x63hgs_content_wrapper\x18\x01 \x01(\x0b\x32\x15.chgs_content_wrapper\x12\x15\n\ridentity_tree\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\"n\n\x19\x63harge_transaction_perist\x12\x1b\n\x13last_transaction_id\x18\x01 \x01(\x05\x12\x16\n\x0elast_id_synced\x18\x02 \x01(\x05\x12\x1c\n\x14transactions_in_file\x18\x03 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_CHGSCONFIG_BOXINSTALLED = _descriptor.EnumDescriptor(
  name='boxinstalled',
  full_name='chgsconfig.boxinstalled',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOX_INSTALLED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=173,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_CHGSCONFIG_BOXINSTALLED)


_CHGSCONFIG = _descriptor.Descriptor(
  name='chgsconfig',
  full_name='chgsconfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='box_is_installed', full_name='chgsconfig.box_is_installed', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='charge_current', full_name='chgsconfig.charge_current', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bluetoothname', full_name='chgsconfig.bluetoothname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='charge_transaction_id', full_name='chgsconfig.charge_transaction_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHGSCONFIG_BOXINSTALLED,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=219,
)


_CHGS_CONTENT_WRAPPER = _descriptor.Descriptor(
  name='chgs_content_wrapper',
  full_name='chgs_content_wrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_uid', full_name='chgs_content_wrapper.command_uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='chgs_content_wrapper.protocol_version', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chgsconfig', full_name='chgs_content_wrapper.chgsconfig', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='certificate', full_name='chgs_content_wrapper.certificate', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='chgs_content_wrapper.command',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=222,
  serialized_end=374,
)


_CHGS_TRANSPORT_WRAPPER = _descriptor.Descriptor(
  name='chgs_transport_wrapper',
  full_name='chgs_transport_wrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chgs_content_wrapper', full_name='chgs_transport_wrapper.chgs_content_wrapper', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identity_tree', full_name='chgs_transport_wrapper.identity_tree', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='chgs_transport_wrapper.signature', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=495,
)


_CHARGE_TRANSACTION_PERIST = _descriptor.Descriptor(
  name='charge_transaction_perist',
  full_name='charge_transaction_perist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_transaction_id', full_name='charge_transaction_perist.last_transaction_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_id_synced', full_name='charge_transaction_perist.last_id_synced', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactions_in_file', full_name='charge_transaction_perist.transactions_in_file', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=607,
)

_CHGSCONFIG.fields_by_name['box_is_installed'].enum_type = _CHGSCONFIG_BOXINSTALLED
_CHGSCONFIG_BOXINSTALLED.containing_type = _CHGSCONFIG
_CHGS_CONTENT_WRAPPER.fields_by_name['chgsconfig'].message_type = _CHGSCONFIG
_CHGS_CONTENT_WRAPPER.fields_by_name['certificate'].message_type = common__pb2._CERTIFICATE
_CHGS_CONTENT_WRAPPER.oneofs_by_name['command'].fields.append(
  _CHGS_CONTENT_WRAPPER.fields_by_name['chgsconfig'])
_CHGS_CONTENT_WRAPPER.fields_by_name['chgsconfig'].containing_oneof = _CHGS_CONTENT_WRAPPER.oneofs_by_name['command']
_CHGS_CONTENT_WRAPPER.oneofs_by_name['command'].fields.append(
  _CHGS_CONTENT_WRAPPER.fields_by_name['certificate'])
_CHGS_CONTENT_WRAPPER.fields_by_name['certificate'].containing_oneof = _CHGS_CONTENT_WRAPPER.oneofs_by_name['command']
_CHGS_TRANSPORT_WRAPPER.fields_by_name['chgs_content_wrapper'].message_type = _CHGS_CONTENT_WRAPPER
DESCRIPTOR.message_types_by_name['chgsconfig'] = _CHGSCONFIG
DESCRIPTOR.message_types_by_name['chgs_content_wrapper'] = _CHGS_CONTENT_WRAPPER
DESCRIPTOR.message_types_by_name['chgs_transport_wrapper'] = _CHGS_TRANSPORT_WRAPPER
DESCRIPTOR.message_types_by_name['charge_transaction_perist'] = _CHARGE_TRANSACTION_PERIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

chgsconfig = _reflection.GeneratedProtocolMessageType('chgsconfig', (_message.Message,), {
  'DESCRIPTOR' : _CHGSCONFIG,
  '__module__' : 'chgs_pb2'
  # @@protoc_insertion_point(class_scope:chgsconfig)
  })
_sym_db.RegisterMessage(chgsconfig)

chgs_content_wrapper = _reflection.GeneratedProtocolMessageType('chgs_content_wrapper', (_message.Message,), {
  'DESCRIPTOR' : _CHGS_CONTENT_WRAPPER,
  '__module__' : 'chgs_pb2'
  # @@protoc_insertion_point(class_scope:chgs_content_wrapper)
  })
_sym_db.RegisterMessage(chgs_content_wrapper)

chgs_transport_wrapper = _reflection.GeneratedProtocolMessageType('chgs_transport_wrapper', (_message.Message,), {
  'DESCRIPTOR' : _CHGS_TRANSPORT_WRAPPER,
  '__module__' : 'chgs_pb2'
  # @@protoc_insertion_point(class_scope:chgs_transport_wrapper)
  })
_sym_db.RegisterMessage(chgs_transport_wrapper)

charge_transaction_perist = _reflection.GeneratedProtocolMessageType('charge_transaction_perist', (_message.Message,), {
  'DESCRIPTOR' : _CHARGE_TRANSACTION_PERIST,
  '__module__' : 'chgs_pb2'
  # @@protoc_insertion_point(class_scope:charge_transaction_perist)
  })
_sym_db.RegisterMessage(charge_transaction_perist)


# @@protoc_insertion_point(module_scope)
